#!/usr/bin/env bash

ORIGINAL_DIR="$PWD"
function finish {
  cd "$ORIGINAL_DIR"
}
trap finish EXIT

SCRIPT="$0"
if [[ -L "$SCRIPT" ]]; then
  # Resolve link to find script
  SCRIPT=$(realpath "$SCRIPT")
fi

SCRIPT_DIR=$(dirname -- "$SCRIPT")
cd "$SCRIPT_DIR"

image/bin/java -m se.dykstrom.standup/se.dykstrom.standup.StandUp "$@"
