#!/usr/bin/env bash

ORIGINAL_DIR="$PWD"
function finish {
  cd "$ORIGINAL_DIR" || exit
}
trap finish EXIT

SCRIPT="$0"
if [[ -L "$SCRIPT" ]]; then
  # Resolve link to find script
  SCRIPT=$(realpath "$SCRIPT")
fi

SCRIPT_DIR=$(dirname -- "$SCRIPT")
cd "$SCRIPT_DIR" || exit

image/bin/java --enable-native-access=javafx.graphics -m se.dykstrom.standup/se.dykstrom.standup.StandUp "$@"
